Repository leaseweb/terraform-provider-leaseweb, pull requests merged in 2024-11, with the labels that each got.

#145 Fix/load balancer datasource
  go.mod
  go.sum
  internal/provider/publiccloud/load_balancers_data_source.go
  internal/provider/publiccloud/load_balancers_data_source_test.go
Labels: bug

#141 feat: implement load balancer listeners data source
  docs/data-sources/public_cloud_load_balancer_listeners.md
  examples/data-sources/leaseweb_public_cloud_load_balancer_listeners/data-source.tf
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/publiccloud/load_balancer_listeners_data_source.go
  internal/provider/publiccloud/load_balancer_listeners_data_source_test.go
Labels: enhancement

#146 feat: implement target groups data source
  ARCHITECTURE.md
  docs/data-sources/public_cloud_target_groups.md
  examples/data-sources/leaseweb_public_cloud_target_groups/data-source.tf
  go.mod
  go.sum
  internal/provider/provider.go
  internal/provider/provider_test.go
  internal/provider/publiccloud/target_groups_data_source.go
  internal/provider/publiccloud/target_groups_data_source_test.go
Labels: enhancement

#172 chore(main): release 1.12.0
  CHANGELOG.md
Labels: autorelease: pending

#180 chore(main): release 1.12.1
  CHANGELOG.md
Labels: autorelease: pending

#193 chore(main): release 1.13.0
  CHANGELOG.md
Labels: autorelease: pending
